---
- name: Configure student VM
  hosts: student_vm
  become: true
  roles:
    - common
    - docker-setup
    - nftables-isolatie
    - student-image
    - guacamole-stack
    - monitoring-agents

- name: Configure monitoring VM
  hosts: monitoring_vm
  become: true
  roles:
    - common
    - docker-setup
    - monitoring-stack
