---
ansible_user: vicuser
ansible_ssh_private_key_file: ~/.ssh/staging
ansible_python_interpreter: /usr/bin/python3

timezone: Europe/Brussels

docker_remap_user: dockremap
docker_remap_uid_start: 165536
docker_remap_uid_count: 65536
