---

vm_role: monitoring

docker_networks:
  - name: lab-monitoring
    bridge_name: lab-monitoring
    subnet: "172.22.0.0/24"
    gateway: "172.22.0.1"

stack_dir: /opt/lab-monitoring

student_vm_ip: "10.14.2.81"
prometheus_scrape_interval: "15s"
prometheus_retention: "90d"

loki_retention_period: "8760h"

grafana_admin_user: admin

monitoring_dir: /opt/lab-monitoring
grafana_admin_pass: "{{ vault_grafana_admin_pass }}"
monitoring_vm_ip: "10.14.2.82"
