---

vm_role: student

docker_networks:
  - name: lab-platform
    bridge_name: lab-platform
    subnet: "172.20.0.0/24"
    gateway: "172.20.0.1"
  - name: lab-students
    bridge_name: lab-students
    subnet: "172.21.0.0/24"
    gateway: "172.21.0.1"

guacd_students_ip: "172.21.0.2"

student_cpu_quota: 50000     
student_cpu_period: 100000
student_memory_limit: "512m"
student_blkio_weight: 100    

class_ttl_seconds: 7200    
homework_ttl_seconds: 604800  

guacamole_version: "1.5.5"
guac_auth_json_version: "1.5.5"

stack_dir: /opt/lab-platform

public_host: "10.14.2.81"
public_url: "https://{{ public_host }}"
monitoring_vm_ip: "10.14.2.82"

